### ISSUE TITLE
[feature request]: higher wattage on non official magsafe chargers

### ISSUE THREAD

**Issue by Hamzabdx** [lich4/ChargeLimiter#74]
Plz add the feature that was added in ios 17.2 that increases the wattage on non official magsafe battery chargers and packs from 5w to 15w
![2ABF991B-E3EB-4FD4-BDEC-B6FD4DF150DA](https://github.com/user-attachments/assets/3a6dc18b-1167-40c4-9e1a-87242c11aa0d)

**Comment by lich4** [comment]
CL is a software, and the functionality of CL heavily depends on the corresponding functionality inside hardware(battery/circuit board) and iOS system kernel, I think there is at least 2 problems to figure out for the feature:
* From which model(iPhone14?15?) the functionality added to the hardware. (The charging protocol is shipped in the hardware(circuit board) to make sure the feature be actived even when the phone power off or system shutdown)
* From which version the iOS system kernel add corresponding support for this feature, maybe lower than 17.2, or maybe just 17.2. If the kernel provide this feature but limited from userspace, then it may be solved.

**Comment by Hamzabdx** [comment]
I have jailbroken (dopamine) iphone 14 pm on ios 16.2 im sure this feature is software based and it was activated in ios 17.4 but it was only activated in iphone 13 and up

**Comment by Hamzabdx** [comment]
[Lynx safemode.txt](https://github.com/user-attachments/files/16319501/Lynx.safemode.txt)

i think this is it

**Comment by Hamzabdx** [comment]
![Uploading D64F00FB-033F-4A0C-84E8-38F4CBA01432.jpeg…]()

**Comment by Hamzabdx** [comment]
Heres an article about it with more detail 
https://www.cnet.com/tech/mobile/iphone-13-and-iphone-14-reportedly-getting-better-wireless-charging-in-ios-17-2/

**Comment by Hamzabdx** [comment]
Btw u can make this feature as a tweak on its own and make it paid on havoc for example id pay 1-2$ dollars for it  if you dont feel like doing it for free

**Comment by Hamzabdx** [comment]
Yes the only way around this is to get magsafe wireless charger clones from china that makes the phone think you have an original or if a dev makes a tweak fixing it

**Comment by lich4** [comment]
The point is whether or not this logic embedded in hardware(the battery or circuit board),and it's probably a handshake phase during charging, and the handshake phase is definitely embedded in hardware, part of the charge protocol.
In this case, it's not possible for software to implement it.

If it is not embedded in hardware, then it may probably resides in system kernel, in this case, it may be possible for software to implement only when there is private interface provided by the kernel, and the private interface can be found with reverse engineering, it's just the way CL born. Why we need an interface instead of calling it directly? it's impossible to call the logic inside the system kernel directly in non-jailbreak environment. (It's possible to do this with PongoOS(checkm8), jailbreak, even hard to do it with only tfp0 for stable implementation)

**Comment by Hamzabdx** [comment]
Its ok

**Comment by lich4** [comment]
I still think it's impossible for a software to implement this. From all the stuff you have shown, it seems probably apple add this new "code" to the kernel, rather than hiding it in lower version system. It's obvious that a software couldn't access kernel directly, espcially for non-jailbreak environment. In this case CL couldn't create new charge logic "code" in kernel, and seems impossible to be implemented.  It may be possible with PongoS environment, jailbreak

**Comment by Hamzabdx** [comment]
The iphones 13pro + already has the ability to charge at 15w its just that its capped at 5w for non official wireless chargers and magsafe powerbanks so the only thing you would be doing is making the ios think its connected to an official apple wireless charger/magsafe when it’s not

**Comment by lich4** [comment]
> The iphones 13pro + already has the ability to charge at 15w on lower ios versions its just that its capped at 5w for non official wireless chargers and magsafe powerbanks so the only thing you would be doing is making the ios think its connected to an official apple wireless charger/magsafe when it’s not

"making the ios think its connected to an official apple", this probably require a kernel hook(this kind of logic generally implemented in kernel or hardware, not userspace), at least jailbreak. Apple itemself definitely won't supply an interface to fake that. So PongoS is still required,  but PongoOS can only exist in model <= iPhone X. So my conclusion is still impossible.

**Comment by Hamzabdx** [comment]
Ok bro
