### ISSUE TITLE
[bug]: magsafe battery keeps auto turning off

### ISSUE THREAD

**Issue by Hamzabdx** [lich4/ChargeLimiter#76]
I always use a magsafe battery pack but while using the temperature charge control feature in charlimiter the battery pack keeps auto turning off i think its because it has an auto turn off function that happens when its not charging for a specific period can you maybe add an option so that charge limiter keeps triggering charging on and off for very small periods even when its in the “no charging” mode when the temperature is too high so that the magsafe battery pack doesn't auto turn off or add something that makes it think that it’s still charging the phone thanks

**Comment by lich4** [comment]
Maybe the battery pack act as an battery bank, triggier the "sleep mode" if amperage lower than some value. or maybe it act as a secondary powersource?
I don't have a magsafe so I'm unable to test it.

**Comment by Hamzabdx** [comment]
Yes I believe it acts as a battery bank its not the official apple magsafe battery pack

**Comment by Hamzabdx** [comment]
I believe it takes about 20-30 seconds for it to auto turn off

**Comment by hashim17** [comment]
Maybe the [Apple MagSafe battery pack](https://pakistanstore.pk/product/apple-magsafe-power-bank-for-iphone/) goes into "sleep mode" when the power it's providing gets too low. Or it could act as a backup power source. I don't have a MagSafe, so I can't test it.

**Comment by Hamzabdx** [comment]
> Maybe the [Apple MagSafe battery pack](https://pakistanstore.pk/product/apple-magsafe-power-bank-for-iphone/) goes into "sleep mode" when the power it's providing gets too low. Or it could act as a backup power source. I don't have a MagSafe, so I can't test it.

no bro if it was a low power issue i would have known since i have one that displays percentage on the bottom of the power back and i wouldnt have opened this bug report

**Comment by Hamzabdx** [comment]
> Maybe the [Apple MagSafe battery pack](https://pakistanstore.pk/product/apple-magsafe-power-bank-for-iphone/) goes into "sleep mode" when the power it's providing gets too low. Or it could act as a backup power source. I don't have a MagSafe, so I can't test it.

no bro if it was a low power issue i would have known since i have one that displays percentage on the bottom of the power back and i wouldnt have opened this bug report

**Comment by lich4** [comment]
As described "battery pack keeps auto turning off", actually it's behaviour of a common "battery bank",  CL only control battery circuilt via system kernel, it is unable to control external powersoruce directly, so it's actually not a bug of CL. 
Based on some feedbacks, there maybe several type of "magsafe", some work well with CL, while others not, this will happen when battery in InhibitCharge status, in which case the amperage will be low enough to trigger the "sleep mode"  of "battery bank" in about 1min generally. 
I won't design a pattern to make it compatible with these special "magsafe battery"s, because it may not compatible with other kinds of "magsafe battery"s, besides, if we make it leave InhibitCharge status, then it will charge again, we can't call it a charge limiter any more. If we don't make it leave InhibitCharge status, then we need to find a way to consume the power, as increase brightness or sth. but I don't think it's a good idea. 
As conclusion, the design of this kind of "battery bank" break everything, this is the source.

**Comment by Hamzabdx** [comment]
It will only be temporary and you can add it only as an option for people likee who want to turn it on 👍
